/**
 * dsh-web-tools — browser client plugin entry.
 *
 * Registers a top-level Settings page (`settings.section`, id `web-tools`)
 * — the same slot contract the official Models / Plugins pages use — so the
 * plugin appears in the Settings nav as "Web Search / 网页搜索", not buried
 * under Plugins → Plugin configuration.
 *
 * The page talks to the Host exclusively through the plugin's fenced
 * `/web-tools/api` HTTP routes (see ../host/routes.ts) — credentials never
 * reach the browser.
 *
 * Copy is registered through the DSH locale service (zh/en dictionaries
 * below). The page follows the DSH UI language by default, and additionally
 * offers its own language selector (Follow system / 中文 / English) that is
 * persisted in the plugin's own config — it never changes the DSH-wide
 * language.
 * @module
 */
import { WebToolsSection } from "./WebToolsSection.tsx";
import { registerSettingsSection, type UiFace } from "./registration.ts";
import { SearchModeButton } from "./SearchModeButton.tsx";
import * as React from "react";
import { useSyncExternalStore } from "react";

/** Locale namespace for this page's copy. */
export const NS = "dsh-web-tools";

/** Services required by this client plugin. */
export const inject = ["slots", "locale"];

/** zh page copy (key-set source of truth). */
export const zhDict: Record<string, string> = {
  nav: "网页搜索",
  title: "网页搜索",
  tagline: "管理搜索源，并在当前搜索源不可用时继续尝试下一项。",
  enabledLabel: "已启用",
  disabledLabel: "已禁用",
  readySummary: "{total} 个 Provider 中 {n} 个可用",
  defaultProviderLabel: "首选",
  orderLabel: "搜索顺序",
  orderHint: "从上到下依次尝试；第一项为默认 Provider",
  editOrder: "编辑顺序",
  providersLabel: "搜索源",
  notInChain: "未加入搜索顺序",
  notInOrder: "未加入",
  notConfigured: "未配置",
  selfHosted: "自建部署",
  ready: "已就绪",
  rateLimited: "暂时不可用",
  authError: "密钥错误",
  unreachable: "无法连接",
  quotaCredits: "{r} / {l} credits",
  quotaRequests: "{r} 次请求{l}",
  quotaUsd: "已用 ${amount}",
  quotaUsdRemaining: "剩余 ${amount}",
  quotaTokens: "{n} tokens",
  updatedJustNow: "刚刚更新",
  updatedAgo: "{mins} 分钟前更新",
  refreshQuota: "刷新额度",
  quotaTitle: "额度",
  resetOn: "重置于 {d}",
  usage: "消耗",
  testSearchTitle: "测试搜索",
  diagnosticsAndMore: "诊断与更多设置",
  searchPlaceholder: "输入查询…",
  search: "搜索",
  searching: "搜索中…",
  clearResult: "清空",
  resultCount: "{n} 个结果",
  attempt: "尝试",
  successOutcome: "成功",
  rateLimitedOutcome: "暂时不可用",
  authOutcome: "密钥错误",
  timeoutOutcome: "超时",
  networkOutcome: "网络错误",
  serverOutcome: "服务端错误",
  abortedOutcome: "已取消",
  configOutcome: "配置错误",
  badRequestOutcome: "请求错误",
  invalidResponseOutcome: "响应异常",
  unknownOutcome: "未知",
  providerStatus: "状态",
  connected: "已连接",
  credentials: "API 密钥",
  keysConfigured: "{n} 个 · 均正常",
  keysSomeIssues: "{n} 个 · 部分异常",
  addKey: "+ 添加 API Key",
  addKeyPlaceholder: "输入 API Key…",
  cancel: "取消",
  add: "添加",
  removeKey: "移除",
  keyReady: "正常",
  keyAuthError: "密钥错误",
  keyNotConfigured: "未配置",
  keyWritableHint: "可写",
  baseUrlLabel: "服务地址",
  baseUrlDefault: "默认",
  baseUrlPlaceholder: "自定义服务地址（留空使用默认）",
  testConnection: "测试连接",
  testingConnection: "测试中…",
  testOk: "连接成功",
  testFail: "连接失败",
  advanced: "更多设置",
  attemptTimeoutLabel: "单个搜索源超时",
  attemptTimeoutHint: "单个搜索源最多等待多久，超时后切换下一家",
  seconds: "{n} 秒",
  save: "保存",
  saved: "已保存",
  saving: "保存中…",
  close: "关闭",
  loading: "正在加载配置…",
  webToolsError: "网页搜索",
  proxyDegradedTitle: "代理不可用",
  proxyDegradedBody: "检测到系统配置了代理，但未找到 undici（代理依赖）——请求将直连发送，走代理的 Provider 可能超时。请在 profile 目录运行 `pnpm install` 后重启。",
  // --- Provider capability descriptions (client-owned copy, never host metadata) ---
  "capability.exa": "搜索 · 网页读取",
  "capability.tavily": "搜索 · 网页提取",
  "capability.brave": "搜索",
  "capability.you": "搜索 · 网页读取",
  "capability.firecrawl": "搜索 · 网页读取",
  "capability.parallel": "搜索 · 网页提取",
  "capability.jina": "搜索 · 网页读取",
  "capability.searxng": "搜索 · 自建",
  connectionSettings: "连接设置",
  connectionDefault: "默认",
  connectionConfigured: "已配置",
  serviceAddress: "服务地址",
  restoreDefaultUrl: "恢复默认",
  enableSourceLabel: "启用此搜索源",
  moveUp: "上移",
  moveDown: "下移",
  makeDefault: "设为默认",
  removeFromChain: "移出搜索顺序",
  addToChain: "加入搜索顺序",
  availableProviders: "可添加",
  noAvailableProviders: "没有可添加的 Provider",
  defaultFirstHint: "第一项为默认 Provider",
  back: "返回",
  quotaUnavailable: "不支持额度查询",
  quotaUnlimited: "按量计费 · 无月度配额",
  quotaSelfHostedShort: "自建部署 · 无平台额度",
  quotaSource: "数据源: {s}",
  quotaSourceApi: "官方",
  quotaSourceResponseHeader: "响应头",
  quotaSourceBestEffortApi: "尽力查询",
  quotaSourceLocalEstimate: "本地估算",
  quotaSourceDashboard: "控制台",
  quotaSourceSelfHosted: "自建部署",
  quotaOverPlan: "剩余 {r} · 计划 {l}",
  quotaSince: "本地已记录 ${amount}",
  searchAuto: "自动",
  autoChain: "自动 · {s}",
  uiLanguage: "语言",
  uiLangAuto: "跟随系统",
  searchModeLabel: "联网搜索",
  searchModeUnavailable: "没有可用的搜索源",
  // --- 搜索顺序 ---
  routingLabel: "搜索顺序",
  routingConfigure: "编辑",
  "routingPolicy.ordered": "优先顺序",
  "routingPolicy.round-robin": "轮流使用",
  "routingPolicy.random": "随机起点",
  "routingPolicyHint.ordered": "从第一项开始，不可用时继续尝试下一项。",
  "routingPolicyHint.round-robin": "每次查询从下一个搜索源开始。",
  "routingPolicyHint.random": "每次查询随机选择一个起始搜索源。",
  routingPolicySection: "使用方式",
  routingSourcesSection: "搜索源",
  routingAvailableSources: "可添加的搜索源",
  routingMinOneSource: "至少保留一个搜索源",
  preferredProviderLabel: "首选",
  disabled: "已停用",
  defaultBadge: "默认",
  adjustedBadge: "已调整",
  unsavedBadge: "未保存",
  restoreDefaults: "恢复默认偏好",
  prefsTitle: "搜索偏好",
  prefsModified: "已修改 {n} 项",
  prefsRestore: "恢复默认",
  prefsCancel: "取消",
  prefsAdjusted: "已调整",
  prefsUnsaved: "未保存",
  prefsSave: "保存",
  prefsSaving: "保存中…",
  prefsSaved: "已保存",
  prefsSaveFailed: "保存失败",
  prefsRestored: "已恢复默认",
  prefsRestoreFailed: "恢复失败",
  moreSettings: "更多设置",
  // --- Provider 偏好控件 (search mode / freshness / native options) ---
  prefsAutoLabel: "自动",
  prefsFast: "快速",
  prefsFastDesc: "减少等待时间",
  prefsInstant: "极速",
  prefsDeep: "深入",
  prefsDeepLite: "轻量",
  prefsDeepReasoning: "推理",
  prefsSpeed: "速度",
  prefsDepth: "深度",
  prefsExaModeLabel: "搜索方式",
  prefsExaAuto: "自动",
  prefsExaAutoDesc: "由 Exa 选择搜索方式",
  prefsExaFast: "快速响应",
  prefsExaFastDesc: "更低延迟，适合简单、明确问题",
  prefsExaDeep: "深度检索",
  prefsExaDeepDesc: "复杂问题 · 较慢",
  prefsExaFreshnessLabel: "内容新鲜度",
  prefsFreshnessAuto: "自动",
  prefsFreshnessLive: "始终刷新",
  prefsFreshnessCache: "仅缓存",
  prefsExaMaxAgeHint: "例如 24 = 优先使用 24 小时内的缓存",
  prefsTavilyDepthLabel: "搜索深度",
  prefsTavilyBasic: "标准",
  prefsTavilyBasicDesc: "日常搜索",
  prefsTavilyAdvanced: "深入",
  prefsTavilyAdvancedDesc: "更高相关性",
  prefsTavilyFast: "快速",
  prefsTavilyFastDesc: "更低延迟",
  prefsTavilyUltraFast: "极速",
  prefsTavilyUltraFastDesc: "最低延迟",
  prefsTavilyAutoParams: "自动调节",
  prefsTavilyAutoParamsDesc: "由 Tavily 根据查询调整参数，单次消耗可能变化",
  prefsTavilyChunksPerSource: "每个来源片段数",
  prefsTavilyExtractDepth: "网页提取",
  prefsExtractBasic: "基础",
  prefsExtractAdvanced: "深入",
  prefsBraveModeLabel: "结果方式",
  prefsBraveAuto: "自动",
  prefsBraveAutoDesc: "优先使用 LLM Context，不可用时继续使用 Web Search",
  prefsBraveLlmContext: "LLM Context",
  prefsBraveLlmContextDesc: "返回经过整理的相关内容",
  prefsBraveWebSearch: "Web Search",
  prefsBraveWebSearchDesc: "返回标准网页搜索结果",
  prefsBraveThreshold: "内容筛选",
  prefsBraveThresholdBalanced: "平衡",
  prefsBraveThresholdStrict: "严格",
  prefsBraveThresholdLenient: "宽松",
  prefsBraveThresholdOff: "关闭",
  prefsBraveTokenBudget: "上下文上限",
  prefsYouResultsLabel: "结果内容",
  prefsYouHighlights: "重点片段",
  prefsYouHighlightsDesc: "返回与查询更相关的内容片段",
  prefsYouSummary: "搜索摘要",
  prefsYouSummaryDesc: "返回基础搜索摘要",
  prefsYouTimeoutSec: "页面读取超时（秒）",
  prefsYouFreshnessSec: "页面缓存新鲜度（秒，0 = 每次刷新）",
  prefsFirecrawlOnlyMain: "只保留正文",
  prefsFirecrawlOnlyMainDesc: "忽略导航、页脚等非正文内容",
  prefsPageCache: "页面缓存",
  prefsFirecrawl1Day: "缓存 1 天",
  prefsFirecrawl7Days: "缓存 7 天",
  prefsParallelQualityLabel: "搜索质量",
  prefsParallelAdvanced: "深入",
  prefsParallelAdvancedDesc: "更适合复杂搜索",
  prefsParallelBasic: "标准",
  prefsParallelBasicDesc: "低延迟，适合明确问题",
  prefsParallelFast: "快速",
  prefsParallelFastDesc: "1 秒延迟预算内的高质量",
  prefsParallelTurbo: "极速",
  prefsParallelTurboDesc: "约 200ms 高吞吐",
  prefsParallelCharsLabel: "返回长度",
  prefsParallelCharsCompact: "精简",
  prefsParallelCharsStandard: "标准",
  prefsParallelCharsMore: "较多",
  prefsJinaModeLabel: "读取方式",
  prefsJinaModeAuto: "自动读取",
  prefsJinaModeAutoDesc: "由 Jina 选择最佳读取方式",
  prefsJinaModeDirect: "直接读取",
  prefsJinaModeDirectDesc: "直接读取页面，通常更快",
  prefsJinaModeBrowser: "浏览器",
  prefsJinaModeBrowserDesc: "完整加载页面，适合动态内容",
  prefsJinaReaderLmLabel: "高质量转换",
  prefsJinaReaderLmDesc: "使用 ReaderLM-v2 处理页面内容，会增加 token 消耗。",
  prefsJinaCacheLabel: "页面缓存",
  prefsJinaCacheAuto: "自动",
  prefsJinaCacheLive: "每次刷新",
  prefsJinaCacheHour: "1 小时",
  prefsJinaCacheDay: "1 天",
  prefsJinaMaxTokens: "返回上限",
  prefsJinaMaxTokensDesc: "限制返回内容的最大 token 数。",
  prefsJinaTokenBudget: "预算上限",
  prefsJinaTokenBudgetDesc: "页面超过该预算时停止请求。",
  // --- 开发者设置 ---
  developerOptions: "调试信息",
  developerOptionsHint: "Provider 原生参数（仅高级用户）",
  developerEffective: "当前生效值",
  developerOverrides: "自定义覆盖",
  developerNoOverrides: "没有覆盖项。",
  developerEdit: "编辑",
  developerEditSave: "保存",
  developerEditCancel: "取消",
  developerParseError: "JSON 格式错误",
  manage: "管理",
  collapse: "收起",
};

/** en page copy, checked complete against the zh key set. */
export const enDict: Record<string, string> = {
  nav: "Web Search",
  title: "Web Search",
  tagline: "Manage search sources and keep trying the next one when the current is unavailable.",
  enabledLabel: "Enabled",
  disabledLabel: "Disabled",
  readySummary: "{n} of {total} providers ready",
  defaultProviderLabel: "Preferred",
  orderLabel: "Search order",
  orderHint: "Providers are tried from top to bottom; the first is the default",
  editOrder: "Edit order",
  providersLabel: "Search sources",
  notInChain: "Not in search chain",
  notConfigured: "Not configured",
  selfHosted: "Self-hosted",
  ready: "Ready",
  rateLimited: "Unavailable",
  authError: "Key error",
  unreachable: "Unreachable",
  quotaCredits: "{r} / {l} credits",
  quotaRequests: "{r} requests{l}",
  quotaUsd: "${amount} used",
  quotaUsdRemaining: "${amount} remaining",
  quotaTokens: "{n} tokens",
  updatedJustNow: "Updated just now",
  updatedAgo: "Updated {mins} min ago",
  refreshQuota: "Refresh quota",
  quotaTitle: "Usage",
  resetOn: "Resets on {d}",
  usage: "Usage",
  testSearchTitle: "Test Search",
  diagnosticsAndMore: "Diagnostics & more settings",
  searchPlaceholder: "Enter a query…",
  search: "Search",
  searching: "Searching…",
  clearResult: "Clear",
  resultCount: "{n} result(s)",
  attempt: "Attempt",
  successOutcome: "Success",
  rateLimitedOutcome: "Unavailable",
  authOutcome: "Key error",
  timeoutOutcome: "Timed out",
  networkOutcome: "Network error",
  serverOutcome: "Server error",
  abortedOutcome: "Cancelled",
  configOutcome: "Config error",
  badRequestOutcome: "Bad request",
  invalidResponseOutcome: "Bad response",
  unknownOutcome: "Unknown",
  providerStatus: "Status",
  connected: "Connected",
  credentials: "API Key",
  keysConfigured: "{n} key(s) · all healthy",
  keysSomeIssues: "{n} key(s) · some issues",
  addKey: "+ Add API key",
  addKeyPlaceholder: "Paste an API key…",
  cancel: "Cancel",
  add: "Add",
  removeKey: "Remove",
  keyReady: "Ready",
  keyAuthError: "Key error",
  keyNotConfigured: "Not configured",
  keyWritableHint: "writable",
  baseUrlLabel: "Service URL",
  baseUrlDefault: "Default",
  baseUrlPlaceholder: "Custom service URL (leave empty for default)",
  testConnection: "Test connection",
  testingConnection: "Testing…",
  testOk: "Connected",
  testFail: "Connection failed",
  advanced: "More settings",
  attemptTimeoutLabel: "Per-source timeout",
  attemptTimeoutHint: "How long one source may run before switching to the next",
  seconds: "{n} seconds",
  save: "Save",
  saved: "Saved",
  saving: "Saving…",
  close: "Close",
  loading: "Loading Web Search configuration…",
  webToolsError: "Web Search",
  proxyDegradedTitle: "Proxy unavailable",
  proxyDegradedBody: "A system proxy is configured, but undici (the proxy dependency) was not found — requests will go out directly, so proxy-dependent providers may time out. Run `pnpm install` in the profile directory and restart.",
  // --- Provider capability descriptions (client-owned copy, never host metadata) ---
  "capability.exa": "Search · Web read",
  "capability.tavily": "Search · Web extract",
  "capability.brave": "Search",
  "capability.you": "Search · Web read",
  "capability.firecrawl": "Search · Web read",
  "capability.parallel": "Search · Web extract",
  "capability.jina": "Search · Web read",
  "capability.searxng": "Search · Self-hosted",
  connectionSettings: "Connection settings",
  connectionDefault: "Default",
  connectionConfigured: "Configured",
  serviceAddress: "Service URL",
  restoreDefaultUrl: "Restore default",
  enableSourceLabel: "Enable this search source",
  moveUp: "Move up",
  moveDown: "Move down",
  makeDefault: "Make default",
  removeFromChain: "Remove from chain",
  addToChain: "Add to chain",
  availableProviders: "Available",
  noAvailableProviders: "No providers to add",
  defaultFirstHint: "First entry is the default provider",
  back: "Back",
  quotaUnavailable: "Quota not supported",
  quotaUnlimited: "Pay-as-you-go · no monthly cap",
  quotaSelfHostedShort: "Self-hosted · no platform quota",
  quotaSource: "Source: {s}",
  quotaSourceApi: "Official",
  quotaSourceResponseHeader: "Response header",
  quotaSourceBestEffortApi: "Best-effort",
  quotaSourceLocalEstimate: "Local estimate",
  quotaSourceDashboard: "Dashboard",
  quotaSourceSelfHosted: "Self-hosted",
  quotaOverPlan: "{r} remaining · plan {l}",
  quotaSince: "${amount} recorded locally",
  searchAuto: "Auto",
  autoChain: "Auto · {s}",
  uiLanguage: "UI language",
  uiLangAuto: "Follow system",
  searchModeLabel: "Web Search",
  searchModeUnavailable: "No search provider available",
  // --- Search order ---
  routingLabel: "Search order",
  routingConfigure: "Edit",
  "routingPolicy.ordered": "Priority order",
  "routingPolicy.round-robin": "Round-robin",
  "routingPolicy.random": "Random start",
  "routingPolicyHint.ordered": "Start from the first source and try the next when unavailable.",
  "routingPolicyHint.round-robin": "Start each query from the next source in turn.",
  "routingPolicyHint.random": "Pick a random starting source for each query.",
  routingPolicySection: "Routing policy",
  routingSourcesSection: "Search sources",
  routingAvailableSources: "Addable sources",
  routingMinOneSource: "Keep at least one search source",
  preferredProviderLabel: "Preferred",
  disabled: "Disabled",
  notInOrder: "Not in order",
  defaultBadge: "Default",
  adjustedBadge: "Adjusted",
  unsavedBadge: "Unsaved",
  restoreDefaults: "Restore default preferences",
  prefsTitle: "Search preferences",
  prefsModified: "{n} item(s) modified",
  prefsRestore: "Restore defaults",
  prefsCancel: "Cancel",
  prefsAdjusted: "Customized",
  prefsUnsaved: "Unsaved",
  prefsSave: "Save",
  prefsSaving: "Saving…",
  prefsSaved: "Saved",
  prefsSaveFailed: "Save failed",
  prefsRestored: "Defaults restored",
  prefsRestoreFailed: "Restore failed",
  moreSettings: "More settings",
  // --- Provider preference controls ---
  prefsAutoLabel: "Auto",
  prefsFast: "Fast",
  prefsFastDesc: "Lower latency",
  prefsInstant: "Instant",
  prefsDeep: "Deep",
  prefsDeepLite: "Lite",
  prefsDeepReasoning: "Reasoning",
  prefsSpeed: "Speed",
  prefsDepth: "Depth",
  prefsExaModeLabel: "Search mode",
  prefsExaAuto: "Auto Select",
  prefsExaAutoDesc: "Best choice for most searches",
  prefsExaFast: "Fast response",
  prefsExaFastDesc: "Lower latency, good for simple queries",
  prefsExaDeep: "Deep search",
  prefsExaDeepDesc: "Complex queries · slower",
  prefsExaFreshnessLabel: "Content freshness",
  prefsFreshnessAuto: "Auto",
  prefsFreshnessLive: "Always fetch",
  prefsFreshnessCache: "Cache only",
  prefsExaMaxAgeHint: "e.g. 24 = prefer content cached within 24 hours",
  prefsTavilyDepthLabel: "Search depth",
  prefsTavilyBasic: "Basic",
  prefsTavilyBasicDesc: "General purpose",
  prefsTavilyAdvanced: "Advanced",
  prefsTavilyAdvancedDesc: "Higher relevance",
  prefsTavilyFast: "Fast",
  prefsTavilyFastDesc: "Lower latency",
  prefsTavilyUltraFast: "Ultra-fast",
  prefsTavilyUltraFastDesc: "Lowest latency",
  prefsTavilyAutoParams: "Auto-tune",
  prefsTavilyAutoParamsDesc: "Tavily adjusts parameters per query; cost may vary",
  prefsTavilyChunksPerSource: "Chunks per source",
  prefsTavilyExtractDepth: "Web extract",
  prefsExtractBasic: "Basic",
  prefsExtractAdvanced: "Advanced",
  prefsBraveModeLabel: "Result mode",
  prefsBraveAuto: "Auto",
  prefsBraveAutoDesc: "Prefer LLM Context, fall back to Web Search",
  prefsBraveLlmContext: "LLM Context",
  prefsBraveLlmContextDesc: "Curated content for LLM ingestion",
  prefsBraveWebSearch: "Web Search",
  prefsBraveWebSearchDesc: "Standard web search results",
  prefsBraveThreshold: "Content filter",
  prefsBraveThresholdBalanced: "Balanced",
  prefsBraveThresholdStrict: "Strict",
  prefsBraveThresholdLenient: "Lenient",
  prefsBraveThresholdOff: "Off",
  prefsBraveTokenBudget: "Context token budget",
  prefsYouResultsLabel: "Result content",
  prefsYouHighlights: "Highlights",
  prefsYouHighlightsDesc: "Passages most relevant to query",
  prefsYouSummary: "Snippet summary",
  prefsYouSummaryDesc: "Basic snippet summaries",
  prefsYouTimeoutSec: "Page crawl timeout (seconds)",
  prefsYouFreshnessSec: "Page cache freshness (seconds, 0 = always live)",
  prefsFirecrawlOnlyMain: "Main content only",
  prefsFirecrawlOnlyMainDesc: "Ignore navigation, footers and non-essential content",
  prefsPageCache: "Page cache",
  prefsFirecrawl1Day: "Cache 1 day",
  prefsFirecrawl7Days: "Cache 7 days",
  prefsParallelQualityLabel: "Search quality",
  prefsParallelAdvanced: "Deep",
  prefsParallelAdvancedDesc: "Suited for complex search queries",
  prefsParallelBasic: "Basic",
  prefsParallelBasicDesc: "Low latency for direct questions",
  prefsParallelFast: "Fast",
  prefsParallelFastDesc: "High quality within ~1s latency budget",
  prefsParallelTurbo: "Turbo",
  prefsParallelTurboDesc: "~200ms high-throughput search",
  prefsParallelCharsLabel: "Return length",
  prefsParallelCharsCompact: "Compact",
  prefsParallelCharsStandard: "Standard",
  prefsParallelCharsMore: "More",
  prefsJinaModeLabel: "Reader engine",
  prefsJinaModeAuto: "Auto reader",
  prefsJinaModeAutoDesc: "Let Jina choose the best reader engine",
  prefsJinaModeDirect: "Direct read",
  prefsJinaModeDirectDesc: "Direct read, typically faster",
  prefsJinaModeBrowser: "Browser",
  prefsJinaModeBrowserDesc: "Full page load, suitable for dynamic content",
  prefsJinaReaderLmLabel: "High quality conversion",
  prefsJinaReaderLmDesc: "Use ReaderLM-v2 to process page content; may increase token consumption.",
  prefsJinaCacheLabel: "Page cache",
  prefsJinaCacheAuto: "Auto",
  prefsJinaCacheLive: "Always fetch",
  prefsJinaCacheHour: "1 hour",
  prefsJinaCacheDay: "1 day",
  prefsJinaMaxTokens: "Return limit",
  prefsJinaMaxTokensDesc: "Max tokens in returned content.",
  prefsJinaTokenBudget: "Budget limit",
  prefsJinaTokenBudgetDesc: "Stop request when the page exceeds this budget.",
  // --- Developer layer / debug info ---
  developerOptions: "Debug Info",
  developerOptionsHint: "",
  developerEffective: "Effective values",
  developerOverrides: "Custom overrides",
  developerNoOverrides: "No overrides.",
  developerEdit: "Edit",
  developerEditSave: "Save",
  developerEditCancel: "Cancel",
  developerParseError: "Invalid JSON",
  manage: "Manage",
  collapse: "Collapse",
};

/** Register the Settings page. */
class SectionErrorBoundary extends React.Component<{ children: React.ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  componentDidCatch(error: Error, info: React.ErrorInfo) {
    console.error("[dsh-web-tools] WebToolsSection render error", error, info);
  }
  render() {
    if (this.state.error !== null) {
      return React.createElement(
        "div",
        { style: { padding: 12, color: "#e5484d", fontFamily: "ui-monospace, monospace", fontSize: 12, whiteSpace: "pre-wrap", lineHeight: 1.5 } },
        "[dsh-web-tools] 页面渲染失败:\n" + (this.state.error.stack ?? String(this.state.error)),
      );
    }
    return this.props.children;
  }
}

function SectionWithBoundary(props: Record<string, unknown>) {
  return React.createElement(SectionErrorBoundary, null, React.createElement(WebToolsSection, props as never));
}

export function apply(ctx: any) {
  ctx.effect(() =>
    ctx.locale.register(NS, {
      zh: zhDict,
      en: enDict,
    }),
  );

  const t = ctx.locale.bind(NS);

  const ui: UiFace = {
    getActiveLocale: () => ctx.locale.getLocale().active,
    subscribeLocale: (fn) => ctx.locale.subscribe(fn),
    zhDict,
    enDict,
  };

  registerSettingsSection(ctx, t, SectionWithBoundary, ui);

  // "联网搜索" per-session toggle — a small always-visible control at the left
  // end of the composer tool row (official `conversation.input.left` seat).
  // Session-scoped: the seat supplies `sessionId` as a standard prop. Because
  // this slot exposes no `inject`, a thin wrapper forwards the sessionId along
  // with locale-localized copy (re-renders when the page language flips).
  const SearchModeControl = (props: { sessionId: string }) => {
    useSyncExternalStore(
      (cb) => ctx.locale.subscribe(cb),
      () => ctx.locale.getLocale().active,
    );
    return React.createElement(SearchModeButton, {
      sessionId: props.sessionId,
      label: t("searchModeLabel"),
      unavailableLabel: t("searchModeUnavailable"),
    });
  };

  ctx.slots.inject("conversation.input.left", () =>
    ctx.slots.register(
      {
        name: "conversation.input.left",
        id: "dsh-web-tools-search-mode",
        order: 30,
        // Localized projected label follows the active locale without re-register.
        label: () => t("searchModeLabel"),
      },
      SearchModeControl,
    ),
  );
}
